### ISSUE TITLE
Flash Issue, cannot call SetVariable to change pages

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosa2#95]
The textbox to jump to a page in the FSI viewer calls the SetVariable(var_name, val) function. On Rosetest, this call results in an error. Security settings related?

**Comment by jabrah** [comment]
Clarification: This occurs while using the FSI viewer, using the GOTO textbox, which is outside of the viewer. Typing a page number and hitting ENTER is supposed to tell the viewer to change to that page. Instead, this error occurs.

**Comment by jabrah** [comment]
```
Sep 21, 2015 12:47:14 PM java.util.logging.LogManager$RootLogger log
SEVERE: Uncaught exception.
com.google.gwt.event.shared.UmbrellaException: Exception caught: (Error) 
 __gwt$exception: <skipped>: Error calling method on NPObject!
	at Unknown.Yg(Unknown Source)
	at Unknown.bh(Unknown Source)
	at Unknown.fh(Unknown Source)
	at Unknown.Et(Unknown Source)
	at Unknown.Ht(Unknown Source)
	at Unknown.Us(Unknown Source)
	at Unknown.HQ(Unknown Source)
	at Unknown.Rp(Unknown Source)
	at Unknown.JQ(Unknown Source)
	at Unknown.Cjb(Unknown Source)
	at Unknown._4(Unknown Source)
	at Unknown.J6(Unknown Source)
	at Unknown.Eh(Unknown Source)
	at Unknown.Ih(Unknown Source)
	at Unknown.Hh/<(Unknown Source)
	at Unknown.anonymous(Unknown Source)
Caused by: com.google.gwt.core.client.JavaScriptException: (Error) 
 __gwt$exception: <skipped>: Error calling method on NPObject!
	at Unknown.s0b(Unknown Source)
	at Unknown.p0b(Unknown Source)
	at Unknown.NLb(Unknown Source)
	at Unknown.uXb(Unknown Source)
	at Unknown.Pq(Unknown Source)
	at Unknown.ct(Unknown Source)
	... 11 more
```

Server log when getting error from Firefox.

**Comment by jabrah** [comment]
In configuring the FSI flash object in the FSI serializer, ALLOW_DOMAINS must specify full sub-domain: rosetest.library.jhu.edu
